### ISSUE TITLE
Flood based on this repo doesn't work

### ISSUE THREAD

**Issue by gulench** [flood-io/demo-gatling#1]
Compilation errors are encountered for the simulation as artifacts inside `page-objects` are not picked for compilation.

If the above is fixed by moving artifacts inside `page-objects` into the `simulations` folder, the simulation is logged as started but no load gets generated. The flood runs for the specified duration but nothing gets done.

**Comment by 90kts** [comment]
Sorry about this - looks like the way we enum directories in the user-files directory has changed. We have since updated this repo with a working example @gulench
